local addon = DiminishingReturns
if not addon then return end

local L = setmetatable({}, {__index = function(self, key)
	if key ~= nil then
		self[key] = tostring(key)
	end
	return tostring(key)
end})
addon.L = L

--------------------------------------------------------------------------------
-- Locales from localization system
--------------------------------------------------------------------------------

-- %Localization: diminishingreturns
-- AUTOMATICALLY GENERATED BY UpdateLocalization.lua
-- ANY CHANGE BELOW THIS LINE WILL BE LOST ON NEXT UPDATE
-- CHANGES SHOULD BE MADE USING http://www.wowace.com/addons/diminishingreturns/localization/

